/* eslint-disable no-param-reassign */
import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { AirtableImage } from '../../shared/models/AirtableImage';
import { AirtableVideo } from '../../shared/models/AirtableVideo';
import { CheckIns } from '../../shared/models/CheckIns';
import { useAppSelector } from '../hooks';
import type { RootState } from '../store';
import { getCheckIns } from '../thunk/checkIns';

// here we are typing the types for the state
export type CheckInsState = {
  data: CheckIns[];
  loading: boolean;
  error: boolean;
};

const initialState: CheckInsState = {
  data: [],
  loading: true,
  error: false,
};

export const checkInsSlice = createSlice({
  name: 'checkIns',
  initialState,
  reducers: {
    setNotes: (
      state,
      action: PayloadAction<{
        id: string;
        notes: string;
      }>,
    ) => {
      const index = state.data.findIndex(
        (data) => data.id === action.payload.id,
      );
      if (index !== -1) {
        state.data[index] = {
          ...state.data[index],
          notes: action.payload.notes,
        };
      }
    },
    setActivityImages: (
      state,
      action: PayloadAction<{
        id: string;
        images: Array<AirtableImage>;
      }>,
    ) => {
      const index = state.data.findIndex(
        (data) => data.id === action.payload.id,
      );
      if (index !== -1) {
        state.data[index] = {
          ...state.data[index],
          images: action.payload.images,
        };
      }
    },
    setActivityVideos: (
      state,
      action: PayloadAction<{
        id: string;
        videos: Array<AirtableVideo>;
      }>,
    ) => {
      const index = state.data.findIndex(
        (data) => data.id === action.payload.id,
      );
      if (index !== -1) {
        state.data[index] = {
          ...state.data[index],
          videos: action.payload.videos,
        };
      }
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere, including actions generated by createAsyncThunk or in other slices.
  // Since this is an API call we have 3 possible outcomes: pending, fulfilled and rejected. We have made allocations for all 3 outcomes.
  // Doing this is good practice as we can tap into the status of the API call and give our users an idea of what's happening in the background.
  extraReducers: (builder) => {
    builder
      .addCase(getCheckIns.pending, (state) => {
        state.loading = true;
      })
      .addCase(getCheckIns.fulfilled, (state, { payload }) => {
        // When the API call is successful and we get some data,the data becomes the `fulfilled` action payload
        state.loading = false;
        state.data = payload;
      })
      .addCase(getCheckIns.rejected, (state) => {
        state.loading = false;
        state.error = true;
      });
  },
});

export const { setNotes, setActivityImages, setActivityVideos } =
  checkInsSlice.actions;

export const useCheckIns = (): CheckIns[] => {
  return useAppSelector((state: RootState) => state.checkIns.data);
};

export const useCheckInsLoading = (): boolean => {
  return useAppSelector((state: RootState) => state.checkIns.loading);
};

export const useActivityNotes = (id: string): string | undefined => {
  return useAppSelector(
    (state: RootState) =>
      state.checkIns.data.find((data) => data.id === id)?.notes,
  );
};

export const useActivityImages = (id: string): AirtableImage[] | undefined => {
  return useAppSelector(
    (state: RootState) =>
      state.checkIns.data.find((data) => data.id === id)?.images || [],
  );
};

export const useActivityVideos = (id: string): AirtableVideo[] | undefined => {
  return useAppSelector(
    (state: RootState) =>
      state.checkIns.data.find((data) => data.id === id)?.videos || [],
  );
};

export default checkInsSlice.reducer;
